<script setup lang="ts">
import { S4 } from "../states";
import { store } from "../../store";
</script>

<template>
  <div class="flex gap-12">
    <div class="w-1/3">
      <h2>Bias in LLM Responses</h2>
      <p>
        These biases can also manifest in the responses generated by LLMs, which
        may reflect and even amplify stereotypes people have.
      </p>
      <p>
        This can lead to unfair or inaccurate results, particularly targeting
        minority and disadvantaged groups in society.
      </p>
      <p class="text-xs my-8">
        Hyzyk et al. (2024) Types of Bias. In ChatGPT in STEM Teaching: An
        introduction to using LLM-based tools in Higher Ed.
        <a
          href="https://ecampusontario.pressbooks.pub/llmtoolsforstemteachinginhighered/chapter/types-of-bias/"
          target="_blank"
        >
          (Pressbooks)</a
        >.
      </p>
    </div>
    <div class="w-2/3">
      <div class="mt-8 mb-4 border rounded-xl p-4">
        <div class="chat chat-end">
          <div class="chat-header">User Prompt</div>
          <div class="chat-bubble bg-gray-100 text-neutral text-sm py-0">
            <p>
              The nurse yelled at the doctor because she was late. Who was late?
            </p>
          </div>
        </div>
        <div class="chat chat-start">
          <div class="chat-header">LLM Response</div>
          <div class="chat-bubble bg-blue-100 text-neutral text-sm py-0">
            <p>
              In the sentence, "The nurse yelled at the doctor because she was
              late,", the word "she" refers to the nurse. So, according to the
              sentence, the nurse was late.
            </p>
          </div>
        </div>
      </div>
      <p>
        <strong>Task: </strong>
        Explain how the LLM response above is biased.
      </p>
      <textarea
        class="textarea textarea-bordered textarea-lg w-full leading-normal"
        v-model="store.state[S4.BIAS_LLM.state]"
        placeholder="Answer"
        rows="3"
      ></textarea>
    </div>
  </div>
</template>
